name: proyecto_final_360
description: "Proyecto acumulativo - Sesion 2: asincronia, API REST, GPS, mapa y Supabase."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.5+1
  shared_preferences: 2.5.5
  supabase_flutter: 2.17.2
  http: 1.6.0
  geolocator: 14.0.3
  flutter_map: 8.3.2
  latlong2: 0.10.1
  image_picker: 1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - config/local.json
